### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by hermanbergwerf** [google/uri.dart#25]
I have a dependency conflict in my project with `quiver`. Maybe you can update the dependencies of this project (among which is `quiver`) to the newest version?

**Comment by hermanbergwerf** [comment]
The quiver dependency is already addressed in #24

**Comment by sanmadjack** [comment]
Is there a chance of an updated pub build with this?

**Comment by hermanbergwerf** [comment]
Seriously? When will this be fixed? This is basically blocking any project from using `quiver` because so many packages import `uri` that a conflict with quiver is almost unavoidable. Last time I fixed this by removing `quiver` and writing some utility functions myself.

**Comment by aaronlademann-wf** [comment]
@justinfagnani this is a blocker for Workiva. The range was widened via #24, but those changes were never published to pub.dartlang.org.

cc/ @sethladd @kevmoo

**Comment by sanmadjack** [comment]
Why was this closed? The version on pub is still not updated with this change.

**Comment by hermanbergwerf** [comment]
Perhaps make a new issue explicitly asking for a pub update.

Op di 1 aug. 2017 om 21:15 schreef Matthew Barbour <notifications@github.com

**Comment by hermanbergwerf** [comment]
I have already worked around this quite a while ago by not using quiver and
implementing things myself. It seems the quiver package has introduced a
number of quite unfortunate conflicts across multiple projects.

Op di 1 aug. 2017 om 22:13 schreef Herman Bergwerf <hermanbergwerf@gmail.com

**Comment by robbecker-wf** [comment]
Looks like there is preparation to release the latest to pub as 0.11.1 as seen in the latest commit.
https://github.com/google/uri.dart/commit/fe1cfca83e21de825e9d6092bc2f96d48c1c2c11

**Comment by mkustermann** [comment]
@sanmadjack Yes, it was closed with the commit fe1cfca and a new version of package:uri has been published with a widened constraint on package:quiver.

Sorry this took so long - seems like nobody was watching this repository and once we knew about the issue, we had to got the permissions sorted out.

**Comment by robbecker-wf** [comment]
Thanks @mkustermann !
